# Generated by Django 5.0.4 on 2024-04-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nozzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='generate_pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
