# Generated by Django 5.0.4 on 2024-04-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nozzle', '0002_pdf_pdf_name_alter_pdf_generate_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_name',
            field=models.CharField(default='Nozzle Demensions', max_length=255),
        ),
    ]
