# Generated by Django 5.0.4 on 2024-04-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nozzle', '0003_alter_pdf_pdf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='file_path',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
